### ISSUE TITLE
Add command shortcuts

### ISSUE THREAD

**Issue by azomDev** [azomDev/pen#3]
allow for `pen a` as an alias for `pen activate`
same thing for `pen d` as an alias for `pen deactivate`
same thing for `pen c` as an alias for `pen create`

**Comment by fedemagnani** [comment]
You might create a opt struct via [clap](https://docs.rs/clap/latest/clap/) or [structopt](https://docs.rs/structopt/latest/structopt/) which would give you way more control in parsing cli inputs and defining short versions for the flag names.

**Comment by azomDev** [comment]
Thanks for the tip! I'll look into that

**Comment by azomDev** [comment]
added in f954e5a663169700aa06e5f7da4d8396a09d6028
